[package]
name = "ehatrom"
version = "0.1.0"
edition = "2024"
description = "EEPROM HAT library for Raspberry Pi HATs (serialization, I2C, CRC32, custom atoms)"
repository = "https://github.com/youruser/ehatrom"
homepage = "https://github.com/youruser/ehatrom"
documentation = "https://docs.rs/ehatrom"
keywords = ["raspberry-pi", "eeprom", "hat", "i2c", "crc32"]
categories = ["embedded", "hardware-support"]
readme = "README.md"
license = "MIT"
authors = ["Your Name <you@example.com>"]

[dependencies]
crc32fast = "1.4.2"
i2cdev = "0.6"
