name: Ehatrom Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ehatrom
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Set nightly as default
        run: rustup default nightly
      - name: Install rustfmt for nightly
        run: rustup component add --toolchain nightly rustfmt
      - name: Check formatting
        run: cargo +nightly fmt -- --check
      - name: Install clippy for nightly
        run: rustup component add --toolchain nightly clippy
      - name: Run clippy
        run: cargo +nightly clippy --workspace --all-targets -- -D warnings
      - name: Build
        run: cargo build --workspace --all-targets --verbose
      - name: Run tests
        run: cargo test --workspace --all-targets --verbose
  release:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ehatrom
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Set nightly as default
        run: rustup default nightly
      - name: Build release
        run: cargo build --release --workspace
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: ehatrom/target/release/
