name: Ehatrom Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ehatrom
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Build
        run: cargo build --workspace --all-targets --verbose
      - name: Run tests
        run: cargo test --workspace --all-targets --verbose
      - name: Generate code coverage
        run: |
          rustup component add llvm-tools-preview
          cargo install grcov
          cargo test --workspace --all-targets --no-fail-fast -- --nocapture
          grcov . -s . -t lcov --llvm --branch --ignore-not-existing -o lcov.info
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ehatrom/lcov.info
  release:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ehatrom
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release
        run: cargo build --release --workspace
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: ehatrom/target/release/
